# Use an official lightweight Python image
FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir requests pandas duckdb

# Default command to run your ETL pipeline
CMD ["python", "main.py"]
